name: Build Image

on: [push, pull_request, workflow_dispatch]

env:
  ENDPOINT: "fancl20/beets-shntool"
  BRANCH: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${ENDPOINT}:latest
            ghcr.io/${ENDPOINT}:${{ github.sha }}
